onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Testbench/clk
add wave -noupdate /Testbench/n_reset
add wave -noupdate /Testbench/button
add wave -noupdate /Testbench/LED
add wave -noupdate /Testbench/RXD
add wave -noupdate /Testbench/TXD
add wave -noupdate /Testbench/sdram_clk
add wave -noupdate /Testbench/sdram_cke
add wave -noupdate /Testbench/sdram_cs_n
add wave -noupdate /Testbench/sdram_wre_n
add wave -noupdate /Testbench/sdram_cas_n
add wave -noupdate /Testbench/sdram_ras_n
add wave -noupdate /Testbench/sdram_a
add wave -noupdate /Testbench/sdram_ba
add wave -noupdate /Testbench/sdram_dqm
add wave -noupdate /Testbench/sdram_dq
add wave -noupdate /Testbench/PVP_inst/SDRAM_controller/init_refresh_count
add wave -noupdate /Testbench/PVP_inst/SDRAM_controller/word_address
add wave -noupdate /Testbench/PVP_inst/SDRAM_controller/init_flag
add wave -noupdate /Testbench/PVP_inst/SDRAM_controller/refresh_flag
add wave -noupdate -radix hexadecimal /Testbench/PVP_inst/SDRAM_controller/state
add wave -noupdate /Testbench/R
add wave -noupdate /Testbench/G
add wave -noupdate /Testbench/B
add wave -noupdate /Testbench/HSYNC
add wave -noupdate /Testbench/VSYNC
add wave -noupdate /Testbench/PRG_address
add wave -noupdate /Testbench/PRG_data
add wave -noupdate /Testbench/CPU_data_address
add wave -noupdate /Testbench/IO_WC
add wave -noupdate /Testbench/IO_RC
add wave -noupdate /Testbench/data_address
add wave -noupdate /Testbench/I_reg
add wave -noupdate /Testbench/I_alternate
add wave -noupdate /Testbench/REGF_A_ADDRESS
add wave -noupdate /Testbench/REGF_W_ADDRESS
add wave -noupdate /Testbench/REGF_WREN
add wave -noupdate /Testbench/REGF_W_DATA
add wave -noupdate /Testbench/REGF_A_DATA
add wave -noupdate /Testbench/REGF_B_DATA
add wave -noupdate /Testbench/NZT
add wave -noupdate /Testbench/XEC
add wave -noupdate /Testbench/JMP
add wave -noupdate /Testbench/CALL
add wave -noupdate /Testbench/RET
add wave -noupdate /Testbench/hazard
add wave -noupdate /Testbench/aux_hazard
add wave -noupdate /Testbench/latch_hazard
add wave -noupdate /Testbench/regf_hazard
add wave -noupdate /Testbench/IO_hazard
add wave -noupdate /Testbench/pipeline_flush
add wave -noupdate /Testbench/decoder_RST
add wave -noupdate /Testbench/amux_out
add wave -noupdate /Testbench/alu_out
add wave -noupdate /Testbench/OVF
add wave -noupdate /Testbench/shift_L4
add wave -noupdate /Testbench/merge_D05
add wave -noupdate /Testbench/stack_addr
add wave -noupdate /Testbench/p_cache_miss
add wave -noupdate /Testbench/d_cache_miss
add wave -noupdate /Testbench/p1_req
add wave -noupdate /Testbench/p1_ready
add wave -noupdate /Testbench/p2_req
add wave -noupdate /Testbench/p2_ready
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {435145 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 203
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {408295 ps} {903565 ps}
